# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               xpzen
tagline:             'serenity now!'
description:         ''
url:                 http://www.xpzen.com
baseurl:             /
paginate:            5

# About/contact
author:
  name:              James Chochlinski
  url:               https://twitter.com/jchochli
  email:             jchochli@xpzen.com

# Custom vars
version:             1.0.0
